spring:
  datasource:
    url: jdbc:postgresql://172.31.138.212:6432/trading-db
    username: nobodysforex
    password: pwd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE