/*
 * API interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jdg.digital.forexbackend.domain.model;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets StrategyEnum
 */
public enum StrategyEnum {
  
  NNR("NNR"),

  STD_FILTERED_CLOSE("STD-Filtered-Close"),

  STD_FILTERED_CLOSE_WITHOUT_REG("STD-Filtered-Close_WITHOUT_REG"),

  NNR_WITHOUT_REG("NNR_WITHOUT_REG"),

  SUPERTREND_AI("SuperTrend AI"),

  SUPERTREND_AI_WITHOUT_REG("SuperTrend AI_WITHOUT_REG"),

  SUPER_AI_TREND("Super_AI_Trend"),
  
  SUPER_AI_TREND_WITHOUT_REG("Super_AI_Trend_WITHOUT_REG"),
  
  _70__STRATEGY("70%_Strategy"),
  
  SSL_HYBRID("SSL_Hybrid"),
  
  SSL_HYBRID_WITHOUT_REG("SSL_Hybrid_WITHOUT_REG"),
  
  AI_VOLUME_SUPERTREND("AI_VOLUME_SUPERTREND"),
  
  SSL___WAVE_TREND_STRATEGY("SSL_+_Wave_Trend_Strategy"),
  
  VHMA("VHMA"),
  
  VHMA_WITHOUT_REG("VHMA_WITHOUT_REG"),
  
  T3FVMA("T3Fvma"),
  
  T3FVMA_WITHOUT_REG("T3Fvma_WITHOUT_REG"),
  
  SENTIMENTRANGEMA("SentimentRangeMa"),
  
  SENTIMENTRANGEMA_WITHOUT_REG("SentimentRangeMa_WITHOUT_REG"),
  
  GAUSSIANCHANNELTRENDAI("GaussianChannelTrendAI"),
  
  GAUSSIANCHANNELTRENDAI_WITHOUT_REG("GaussianChannelTrendAI_WITHOUT_REG"),
  
  T3_LOCALLYWEIGHTEDREGRESSION("T3_LocallyWeightedRegression"),
  
  T3_LOCALLYWEIGHTEDREGRESSION_WITHOUT_REG("T3_LocallyWeightedRegression_WITHOUT_REG"),
  
  T3_HMAKAHLMAN("T3_HmaKahlman"),
  
  T3_HMAKAHLMAN_WITHOUT_REG("T3_HmaKahlman_WITHOUT_REG"),
  
  T3_JMACROSSOVER("T3_JMaCrossover"),
  
  T3_JMACROSSOVER_WITHOUT_REG("T3_JMaCrossover_WITHOUT_REG"),
  
  T3_MACHINELEARNINGLOGISTICREGRESSION("T3_MachineLearningLogisticRegression"),
  
  T3_MACHINELEARNINGLOGISTICREGRESSION_WITHOUT_REG("T3_MachineLearningLogisticRegression_WITHOUT_REG"),
  
  T3_GAPFILLING("T3_GapFilling"),
  
  T3_GAPFILLING_WITHOUT_REG("T3_GapFilling_WITHOUT_REG"),
  
  T3_EVWMAVWAPMACD("T3_EvwmaVwapMacd"),
  
  T3_EVWMAVWAPMACD_WITHOUT_REG("T3_EvwmaVwapMacd_WITHOUT_REG"),
  
  T3_BOLLINGERBANDSPINBAR("T3_BollingerBandsPinbar"),
  
  T3_BOLLINGERBANDSPINBAR_WITHOUT_REG("T3_BollingerBandsPinbar_WITHOUT_REG"),
  
  T3_TRENDAI("T3_TrendAI"),
  
  T3_TRENDAI_WITHOUT_REG("T3_TrendAI_WITHOUT_REG"),
  
  T3_NNFX("T3_NNFX"),
  
  T3_NNFX_WITHOUT_REG("T3_NNFX_WITHOUT_REG"),
  
  T3_EFFICIENTTRENDSTEPMOD("T3_EfficientTrendStepMod"),
  
  T3_EFFICIENTTRENDSTEPMOD_WITHOUT_REG("T3_EfficientTrendStepMod_WITHOUT_REG"),
  
  T3_AROONBASED("T3_AroonBased"),
  
  T3_AROONBASED_WITHOUT_REG("T3_AroonBased_WITHOUT_REG"),
  
  T3_EMASTRATEGY("T3_EmaStrategy"),
  
  T3_EMASTRATEGY_WITHOUT_REG("T3_EmaStrategy_WITHOUT_REG"),
  
  SOTT_LORENTZIAN("SOTT_Lorentzian"),
  
  SOTT_LORENTZIAN_WITHOUT_REG("SOTT_Lorentzian_WITHOUT_REG"),
  
  RSS_WMA("RSS_WMA"),
  
  RSS_WMA_WITHOUT_WITHOUT_REG("RSS_WMA_WITHOUT_WITHOUT_REG"),
  
  T3_MESAPHASOR("T3_MesaPhasor"),
  
  T3_MESAPHASOR_WITHOUT_REG("T3_MesaPhasor_WITHOUT_REG"),
  
  T3_SUPPORTANDRESISTANCELEVELS("T3_SupportAndResistanceLevels"),
  
  T3_SUPPORTANDRESISTANCELEVELS_WITHOUT_REG("T3_SupportAndResistanceLevels_WITHOUT_REG"),
  
  T3_EAMS("T3_Eams"),
  
  T3_EAMS_WITHOUT_REG("T3_EAMS_WITHOUT_REG"),
  
  T3_VOLUMEDIFFERENCEDELTACYCLEOSCILLATOR("T3_VolumeDifferenceDeltaCycleOscillator"),
  
  T3_VOLUMEDIFFERENCEDELTACYCLEOSCILLATOR_WITHOUT_REG("T3_VolumeDifferenceDeltaCycleOscillator_WITHOUT_REG"),
  
  T3_MACDSCALP("T3_MacdScalp"),
  
  T3_MACDSCALP_WITHOUT_REG("T3_MacdScalp_WITHOUT_REG"),
  
  T3_DICROSSINGDAILY("T3_DiCrossingDaily"),
  
  T3_DICROSSINGDAILY_WITHOUT_REG("T3_DiCrossingDaily_WITHOUT_REG"),
  
  T3_HALFTREND("T3_HalfTrend"),
  
  T3_HALFTREND_WITHOUT_REG("T3_HalfTrend_WITHOUT_REG"),
  
  T3_BERNOULLIENTROPYFUNCTION("T3_BernoulliEntropyFunction"),
  
  T3_BERNOULLIENTROPYFUNCTION_WITHOUT_REG("T3_BernoulliEntropyFunction_WITHOUT_REG"),
  
  T3_LINEARTREND("T3_LinearTrend"),
  
  T3_LINEARTREND_WITHOUT_REG("T3_LinearTrend_WITHOUT_REG"),
  
  T3_UTBOT("T3_UtBot"),
  
  T3_UTBOT_WITHOUT_REG("T3_UtBot_WITHOUT_REG"),
  
  T3_PIVOTPOINTSUPERTREND("T3_PivotPointSuperTrend"),
  
  T3_PIVOTPOINTSUPERTREND_WITHOUT_REG("T3_PivotPointSuperTrend_WITHOUT_REG"),
  
  T3_ANTIBREAKOUT("T3_AntiBreakout"),
  
  T3_ANTIBREAKOUT_WITHOUT_REG("T3_AntiBreakout_WITHOUT_REG"),
  
  T3_LUBE("T3_Lube"),
  
  T3_LUBE_WITHOUT_REG("T3_Lube_WITHOUT_REG"),
  
  T3_THIRDWAVE("T3_ThirdWave"),
  
  T3_THIRDWAVE_WITHOUT_REG("T3_ThirdWave_WITHOUT_REG"),
  
  T3_PINBARSTRATEGY("T3_PinBarStrategy"),
  
  T3_PINBARSTRATEGY_WITHOUT_REG("T3_PinBarStrategy_WITHOUT_REG"),
  
  T3_REVERSALFINDER("T3_ReversalFinder"),
  
  T3_REVERSALFINDER_WITHOUT_REG("T3_ReversalFinder_WITHOUT_REG"),
  
  T3_MACDHISTOGRAM_LLTDEMA("T3_MacdHistogram_LLTDEMA"),
  
  T3_MACDHISTOGRAM_LLTDEMA_WITHOUT_REG("T3_MacdHistogram_LLTDEMA_WITHOUT_REG"),
  
  T3_MACDHISTOGRAM_TDEMA("T3_MacdHistogram_TDEMA"),
  
  T3_MACDHISTOGRAM_TDEMA_WITHOUT_REG("T3_MacdHistogram_TDEMA_WITHOUT_REG"),
  
  T3_MACDHISTOGRAM_DEMA("T3_MacdHistogram_DEMA"),
  
  T3_MACDHISTOGRAM_DEMA_WITHOUT_REG("T3_MacdHistogram_DEMA_WITHOUT_REG"),
  
  T3_MACDHISTOGRAM_EMA("T3_MacdHistogram_EMA"),
  
  T3_MACDHISTOGRAM_EMA_WITHOUT_REG("T3_MacdHistogram_EMA_WITHOUT_REG"),
  
  T3_MACDHISTOGRAM_THMA("T3_MacdHistogram_THMA"),
  
  T3_MACDHISTOGRAM_THMA_WITHOUT_REG("T3_MacdHistogram_THMA_WITHOUT_REG"),
  
  T3_MACDHISTOGRAM_ZLEMA("T3_MacdHistogram_ZLEMA"),
  
  T3_MACDHISTOGRAM_ZLEMA_WITHOUT_REG("T3_MacdHistogram_ZLEMA_WITHOUT_REG"),
  
  T3VMACDHISTOGRAM_ZLTEMA("T3vMacdHistogram_ZLTEMA"),
  
  T3_MACDHISTOGRAM_ZLTEMA_WITHOUT_REG("T3_MacdHistogram_ZLTEMA_WITHOUT_REG"),
  
  T3_NEUTRONIXAI("T3_NeutronixAi"),
  
  T3_NEUTRONIXAI_WITHOUT_REG("T3_NeutronixAi_WITHOUT_REG"),
  
  T3_NEUTRONIXSWING("T3_NeutronixSwing"),
  
  T3_NEUTRONIXSWING_WITHOUT_REG("T3_NeutronixSwing_WITHOUT_REG"),
  
  T3_NEUTRONIXSCALPING("T3_NeutronixScalping"),
  
  T3_NEUTRONIXSCALPING_WITHOUT_REG("T3_NeutronixScalping_WITHOUT_REG"),
  
  T3_THREECOMMASBOTSTRATEGY_EMA("T3_ThreeCommasBotStrategy_EMA"),
  
  T3_THREECOMMASBOTSTRATEGY_EMA_WITHOUT_REG("T3_ThreeCommasBotStrategy_EMA_WITHOUT_REG"),
  
  T3_THREECOMMASBOTSTRATEGY_HEMA("T3_ThreeCommasBotStrategy_HEMA"),
  
  T3_THREECOMMASBOTSTRATEGY_HEMA_WITHOUT_REG("T3_ThreeCommasBotStrategy_HEMA_WITHOUT_REG"),
  
  T3_THREECOMMASBOTSTRATEGY_SMA("T3_ThreeCommasBotStrategy_SMA"),
  
  T3_THREECOMMASBOTSTRATEGY_SMA_WITHOUT_REG("T3_ThreeCommasBotStrategy_SMA_WITHOUT_REG"),
  
  T3_THREECOMMASBOTSTRATEGY_HMA("T3_ThreeCommasBotStrategy_HMA"),
  
  T3_THREECOMMASBOTSTRATEGY_HMA_WITHOUT_REG("T3_ThreeCommasBotStrategy_HMA_WITHOUT_REG"),
  
  T3_THREECOMMASBOTSTRATEGY_WMA("T3_ThreeCommasBotStrategy_WMA"),
  
  T3_THREECOMMASBOTSTRATEGY_WMA_WITHOUT_REG("T3_ThreeCommasBotStrategy_WMA_WITHOUT_REG"),
  
  T3_THREECOMMASBOTSTRATEGY_DEMA("T3_ThreeCommasBotStrategy_DEMA"),
  
  T3_THREECOMMASBOTSTRATEGY_DEMA_WITHOUT_REG("T3_ThreeCommasBotStrategy_DEMA_WITHOUT_REG"),
  
  T3_THREECOMMASBOTSTRATEGY_VWMA("T3_ThreeCommasBotStrategy_VWMA"),
  
  T3_THREECOMMASBOTSTRATEGY_VWMA_WITHOUT_REG("T3_ThreeCommasBotStrategy_VWMA_WITHOUT_REG"),
  
  T3_THREECOMMASBOTSTRATEGY_VWAP("T3_ThreeCommasBotStrategy_VWAP"),
  
  T3_THREECOMMASBOTSTRATEGY_VWAP_WITHOUT_REG("T3_ThreeCommasBotStrategy_VWAP_WITHOUT_REG"),
  
  T3_THREECOMMASBOTSTRATEGY_T3("T3_ThreeCommasBotStrategy_T3"),
  
  T3_THREECOMMASBOTSTRATEGY_T3_WITHOUT_REG("T3_ThreeCommasBotStrategy_T3_WITHOUT_REG"),
  
  T3_MOMENTUMBASEDZIGZAG("T3_MomentumBasedZigZag"),
  
  T3_MOMENTUMBASEDZIGZAG_WITHOUT_REG("T3_MomentumBasedZigZag_WITHOUT_REG"),
  
  T3_DEKIDAKAASHISIGNALS("T3_DekidakaAshiSignals"),
  
  T3_DEKIDAKAASHISIGNALS_WITHOUT_REG("T3_DekidakaAshiSignals_WITHOUT_REG"),
  
  T3_SUPERTRENDCLEANED("T3_SuperTrendCleaned"),
  
  T3_SUPERTRENDCLEANED_WITHOUT_REG("T3_SuperTrendCleaned_WITHOUT_REG"),
  
  T3_SCALEDNORMALIZEDVECTOR("T3_ScaledNormalizedVector"),
  
  T3_SCALEDNORMALIZEDVECTOR_WITHOUT_REG("T3_ScaledNormalizedVector_WITHOUT_REG"),
  
  T3_RANGEFILTERS("T3_RangeFilters"),
  
  T3_RANGEFILTERS_WITHOUT_REG("T3_RangeFilters_WITHOUT_REG"),
  
  T3_NEUTRONIXDCAEMU("T3_NeutronixDCAemu"),
  
  T3_NEUTRONIXDCAEMU_WITHOUT_REG("T3_NeutronixDCAemu_WITHOUT_REG"),
  
  T3_UHLMASYSTEM("T3_UhlMASystem"),
  
  T3_UHLMASYSTEM_WITHOUT_REG("T3_UhlMASystem_WITHOUT_REG"),
  
  T3_LLORENSACTIVATOR("T3_LlorensActivator"),
  
  T3_LLORENSACTIVATOR_WITHOUT_REG("T3_LlorensActivator_WITHOUT_REG"),
  
  T3_CUSTOMSUPERTRENDCLEANED("T3_CustomSuperTrendCleaned"),
  
  T3_CUSTOMSUPERTRENDCLEANED_WITHOUT_REG("T3_CustomSuperTrendCleaned_WITHOUT_REG"),
  
  T3_BILATERALSTOCHASTICOSCILLATOR("T3_BilateralStochasticOscillator"),
  
  T3_BILATERALSTOCHASTICOSCILLATOR_WITHOUT_REG("T3_BilateralStochasticOscillator_WITHOUT_REG"),
  
  T3_NICKRYPOCKTRAILINGREVERSE("T3_NickRypockTrailingReverse"),
  
  T3_NICKRYPOCKTRAILINGREVERSE_WITHOUT_REG("T3_NickRypockTrailingReverse_WITHOUT_REG"),
  
  T3_GRIDLIKE("T3_GridLike"),
  
  T3_GRIDLIKE_WITHOUT_REG("T3_GridLike_WITHOUT_REG"),
  
  ADXCROSSOVER_M15("AdxCrossover_M15"),
  
  ADXCROSSOVER_H1("AdxCrossover_H1"),
  
  ADXCROSSOVER_H4("AdxCrossover_H4"),
  
  ADXEMA14_M15("ADXEMA14_M15"),
  
  ADXEMA14_H1("ADXEMA14_H1"),
  
  ADXEMA14_H4("ADXEMA14_H4"),
  
  ADXRSI_M15("AdxRsi_M15"),
  
  ADXRSI_H1("AdxRsi_H1"),
  
  ADXRSI_H4("AdxRsi_H4"),
  
  AROONADX_M15("AroonAdx_M15"),
  
  AROONADX_H1("AroonAdx_H1"),
  
  AROONADX_H4("AroonAdx_H4"),
  
  AROONINDICATOR_M15("AroonIndicator_M15"),
  
  AROONINDICATOR_H1("AroonIndicator_H1"),
  
  AROONINDICATOR_H4("AroonIndicator_H4"),
  
  AWESOMEOSCILLATOR_M15("AwesomeOscillator_M15"),
  
  AWESOMEOSCILLATOR_H1("AwesomeOscillator_H1"),
  
  AWESOMEOSCILLATOR_H4("AwesomeOscillator_H4"),
  
  AWESOMEOSCILLATORSAUCER_M15("AwesomeOscillatorSaucer_M15"),
  
  AWESOMEOSCILLATORSAUCER_H1("AwesomeOscillatorSaucer_H1"),
  
  AWESOMEOSCILLATORSAUCER_H4("AwesomeOscillatorSaucer_H4"),
  
  BLADERUNNER_M15("BladeRunner_M15"),
  
  BLADERUNNER_H1("BladeRunner_H1"),
  
  BLADERUNNER_H4("BladeRunner_H4"),
  
  BOLLINGERBANDSANDRSI_M15("BollingerBandsAndRSI_M15"),
  
  BOLLINGERBANDSANDRSI_H1("BollingerBandsAndRSI_H1"),
  
  BOLLINGERBANDSANDRSI_H4("BollingerBandsAndRSI_H4"),
  
  BOLLINGERBANDSANDRSI2_M15("BollingerBandsAndRSI2_M15"),
  
  BOLLINGERBANDSANDRSI2_H1("BollingerBandsAndRSI2_H1"),
  
  BOLLINGERBANDSANDRSI2_H4("BollingerBandsAndRSI2_H4"),
  
  CCIMACDPSAR_M15("CciMacdPsar_M15"),
  
  CCIMACDPSAR_H1("CciMacdPsar_H1"),
  
  CCIMACDPSAR_H4("CciMacdPsar_H4"),
  
  CCIMOVINGAVERAGE_M15("CciMovingAverage_M15"),
  
  CCIMOVINGAVERAGE_H1("CciMovingAverage_H1"),
  
  CCIMOVINGAVERAGE_H4("CciMovingAverage_H4"),
  
  COMMODITYCHANNELINDEX_M15("CommodityChannelIndex_M15"),
  
  COMMODITYCHANNELINDEX_H1("CommodityChannelIndex_H1"),
  
  COMMODITYCHANNELINDEX_H4("CommodityChannelIndex_H4"),
  
  DONCHIANATR_M15("DonchianATR_M15"),
  
  DONCHIANATR_H1("DonchianATR_H1"),
  
  DONCHIANATR_H4("DonchianATR_H4"),
  
  DONCHIANBREAKOUT_M15("DonchianBreakout_M15"),
  
  DONCHIANBREAKOUT_H1("DonchianBreakout_H1"),
  
  DONCHIANBREAKOUT_H4("DonchianBreakout_H4"),
  
  DONCHIANMIDDLE_M15("DonchianMiddle_M15"),
  
  DONCHIANMIDDLE_H1("DonchianMiddle_H1"),
  
  DONCHIANMIDDLE_H4("DonchianMiddle_H4"),
  
  DPOCANDLESTICK_M15("DpoCandlestick_M15"),
  
  DPOCANDLESTICK_H1("DpoCandlestick_H1"),
  
  DPOCANDLESTICK_H4("DpoCandlestick_H4"),
  
  ELDERRAY_M15("ElderRay_M15"),
  
  ELDERRAY_H1("ElderRay_H1"),
  
  ELDERRAY_H4("ElderRay_H4"),
  
  ELDERRAYALTERNATIVE_M15("ElderRayAlternative_M15"),
  
  ELDERRAYALTERNATIVE_H1("ElderRayAlternative_H1"),
  
  ELDERRAYALTERNATIVE_H4("ElderRayAlternative_H4"),
  
  THREEEMA_M15("ThreeEma_M15"),
  
  THREEEMA_H1("ThreeEma_H1"),
  
  THREEEMA_H4("ThreeEma_H4"),
  
  THREEEMAALTERNATIVE_M15("ThreeEmaAlternative_M15"),
  
  THREEEMAALTERNATIVE_H1("ThreeEmaAlternative_H1"),
  
  THREEEMAALTERNATIVE_H4("ThreeEmaAlternative_H4"),
  
  EMACROSSOVER_M15("EMACrossover_M15"),
  
  EMACROSSOVER_H1("EMACrossover_H1"),
  
  EMACROSSOVER_H4("EMACrossover_H4"),
  
  EMACROSSOVERALTERNATIVE_M15("EMACrossoverAlternative_M15"),
  
  EMACROSSOVERALTERNATIVE_H1("EMACrossoverAlternative_H1"),
  
  EMACROSSOVERALTERNATIVE_H4("EMACrossoverAlternative_H4"),
  
  EMACROSSOVERRSI_M15("EMACrossoverRSI_M15"),
  
  EMACROSSOVERRSI_H1("EMACrossoverRSI_H1"),
  
  EMACROSSOVERRSI_H4("EMACrossoverRSI_H4"),
  
  EMACROSSOVERRSIALTERNATIVE_M15("EMACrossoverRSIAlternative_M15"),
  
  EMACROSSOVERRSIALTERNATIVE_H1("EMACrossoverRSIAlternative_H1"),
  
  EMACROSSOVERRSIALTERNATIVE_H4("EMACrossoverRSIAlternative_H4"),
  
  EMAMACDRSI_M15("EMAMACDRSI_M15"),
  
  EMAMACDRSI_H1("EMAMACDRSI_H1"),
  
  EMAMACDRSI_H4("EMAMACDRSI_H4"),
  
  EMAMI_M15("EMAMI_M15"),
  
  EMAMI_H1("EMAMI_H1"),
  
  EMAMI_H4("EMAMI_H4"),
  
  FORCEINDEXEMA_M15("ForceIndexEMA_M15"),
  
  FORCEINDEXEMA_H1("ForceIndexEMA_H1"),
  
  FORCEINDEXEMA_H4("ForceIndexEMA_H4"),
  
  KELTNERSTOCHASTICADX_M15("KeltnerStochasticAdx_M15"),
  
  KELTNERSTOCHASTICADX_H1("KeltnerStochasticAdx_H1"),
  
  KELTNERSTOCHASTICADX_H4("KeltnerStochasticAdx_H4"),
  
  KAMA_M15("KAMA_M15"),
  
  KAMA_H1("KAMA_H1"),
  
  KAMA_H4("KAMA_H4"),
  
  KAMACROSSOVER_M15("KAMACrossover_M15"),
  
  KAMACROSSOVER_H1("KAMACrossover_H1"),
  
  KAMACROSSOVER_H4("KAMACrossover_H4"),
  
  KELTNERADX_M15("KeltnerAdx_M15"),
  
  KELTNERADX_H1("KeltnerAdx_H1"),
  
  KELTNERADX_H4("KeltnerAdx_H4"),
  
  KELTNERRSI_M15("KeltnerRsi_M15"),
  
  KELTNERRSI_H1("KeltnerRsi_H1"),
  
  KELTNERRSI_H4("KeltnerRsi_H4"),
  
  KELTNERSTOCHASTIC_M15("KeltnerStochastic_M15"),
  
  KELTNERSTOCHASTIC_H1("KeltnerStochastic_H1"),
  
  KELTNERSTOCHASTIC_H4("KeltnerStochastic_H4"),
  
  MACDCROSSOVER_M15("MACDCrossover_M15"),
  
  MACDCROSSOVER_H1("MACDCrossover_H1"),
  
  MACDCROSSOVER_H4("MACDCrossover_H4"),
  
  MACDHISTOGRAMREVERSAL_M15("MACDHistogramReversal_M15"),
  
  MACDHISTOGRAMREVERSAL_H1("MACDHistogramReversal_H1"),
  
  MACDHISTOGRAMREVERSAL_H4("MACDHistogramReversal_H4"),
  
  MACDRSISMA_M15("MacdRsiSma_M15"),
  
  MACDRSISMA_H1("MacdRsiSma_H1"),
  
  MACDRSISMA_H4("MacdRsiSma_H4"),
  
  MACDSTOCHASTICCROSSOVER_M15("MACDStochasticCrossover_M15"),
  
  MACDSTOCHASTICCROSSOVER_H1("MACDStochasticCrossover_H1"),
  
  MACDSTOCHASTICCROSSOVER_H4("MACDStochasticCrossover_H4"),
  
  MACDZEROCROSS_M15("MACDZeroCross_M15"),
  
  MACDZEROCROSS_H1("MACDZeroCross_H1"),
  
  MACDZEROCROSS_H4("MACDZeroCross_H4"),
  
  MFI_M15("MFI_M15"),
  
  MFI_H1("MFI_H1"),
  
  MFI_H4("MFI_H4"),
  
  OOPSSIGNALS_M15("OopsSignals_M15"),
  
  OOPSSIGNALS_H1("OopsSignals_H1"),
  
  OOPSSIGNALS_H4("OopsSignals_H4"),
  
  PSARMOVINGAVERAGE_M15("PsarMovingAverage_M15"),
  
  PSARMOVINGAVERAGE_H1("PsarMovingAverage_H1"),
  
  PSARMOVINGAVERAGE_H4("PsarMovingAverage_H4"),
  
  RSI2_M15("Rsi2_M15"),
  
  RSI2_H1("Rsi2_H1"),
  
  RSI2_H4("Rsi2_H4"),
  
  RSI8020_M15("Rsi8020_M15"),
  
  RSI8020_H1("Rsi8020_H1"),
  
  RSI8020_H4("Rsi8020_H4"),
  
  SIMPLEMAEXPONENTIALMA_M15("SimpleMAExponentialMA_M15"),
  
  SIMPLEMAEXPONENTIALMA_H1("SimpleMAExponentialMA_H1"),
  
  SIMPLEMAEXPONENTIALMA_H4("SimpleMAExponentialMA_H4"),
  
  SIMPLEMAEXPONENTIALMAALTERNATIVE_M15("SimpleMAExponentialMAAlternative_M15"),
  
  SIMPLEMAEXPONENTIALMAALTERNATIVE_H1("SimpleMAExponentialMAAlternative_H1"),
  
  SIMPLEMAEXPONENTIALMAALTERNATIVE_H4("SimpleMAExponentialMAAlternative_H4"),
  
  SMAMI_M15("SMAMI_M15"),
  
  SMAMI_H1("SMAMI_H1"),
  
  SMAMI_H4("SMAMI_H4"),
  
  STOCHASTICOSCILLATORNOEXIT_M15("StochasticOscillatorNoExit_M15"),
  
  STOCHASTICOSCILLATORNOEXIT_H1("StochasticOscillatorNoExit_H1"),
  
  STOCHASTICOSCILLATORNOEXIT_H4("StochasticOscillatorNoExit_H4"),
  
  TRIPLEBOLLINGERBANDS_M15("TripleBollingerBands_M15"),
  
  TRIPLEBOLLINGERBANDS_H1("TripleBollingerBands_H1"),
  
  TRIPLEBOLLINGERBANDS_H4("TripleBollingerBands_H4"),
  
  TRIXEMA_M15("TrixEma_M15"),
  
  TRIXEMA_H1("TrixEma_H1"),
  
  TRIXEMA_H4("TrixEma_H4"),
  
  TRIXMI_M15("TrixMI_M15"),
  
  TRIXMI_H1("TrixMI_H1"),
  
  TRIXMI_H4("TrixMI_H4"),
  
  TRIXRSI_M15("TrixRsi_M15"),
  
  TRIXRSI_H1("TrixRsi_H1"),
  
  TRIXRSI_H4("TrixRsi_H4"),
  
  TSICROSSOVER_M15("TSICrossover_M15"),
  
  TSICROSSOVER_H1("TSICrossover_H1"),
  
  TSICROSSOVER_H4("TSICrossover_H4"),
  
  VORTEXCROSSOVER_M15("VortexCrossover_M15"),
  
  VORTEXCROSSOVER_H1("VortexCrossover_H1"),
  
  VORTEXCROSSOVER_H4("VortexCrossover_H4"),
  
  VORTEXSMA_M15("VortexSma_M15"),
  
  VORTEXSMA_H1("VortexSma_H1"),
  
  VORTEXSMA_H4("VortexSma_H4"),
  
  WILLIAMSINDICATOR_M15("WilliamsIndicator_M15"),
  
  WILLIAMSINDICATOR_H1("WilliamsIndicator_H1"),
  
  WILLIAMSINDICATOR_H4("WilliamsIndicator_H4"),
  
  WILLIAMSRSI_M15("WilliamsRsi_M15"),
  
  WILLIAMSRSI_H1("WilliamsRsi_H1"),
  
  WILLIAMSRSI_H4("WilliamsRsi_H4"),
  
  WILLIAMSSTOCHASTIC_M15("WilliamsStochastic_M15"),
  
  WILLIAMSSTOCHASTIC_H1("WilliamsStochastic_H1"),
  
  WILLIAMSSTOCHASTIC_H4("WilliamsStochastic_H4"),
  
  ZIGZAG_M15("ZigZag_M15"),
  
  ZIGZAG_H1("ZigZag_H1"),
  
  ZIGZAG_H4("ZigZag_H4"),
  
  EMACROSSOVERMACD_M15("EMACrossoverMACD_M15"),
  
  EMACROSSOVERMACD_H1("EMACrossoverMACD_H1"),
  
  EMACROSSOVERMACD_H4("EMACrossoverMACD_H4");

  private String value;

  StrategyEnum(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static StrategyEnum fromValue(String value) {
    for (StrategyEnum b : StrategyEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    if (prefix == null) {
      prefix = "";
    }

    return String.format("%s=%s", prefix, this.toString());
  }

}

