/*
 * API interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jdg.digital.forexbackend.domain.model;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets SymbolEnum
 */
public enum SymbolEnum {
  
  AUDCHF("AUDCHF"),
  
  EURUSD("EURUSD"),
  
  GBPUSD("GBPUSD"),
  
  USDJPY("USDJPY"),
  
  USDCHF("USDCHF"),
  
  USDCAD("USDCAD"),
  
  AUDUSD("AUDUSD"),
  
  NZDUSD("NZDUSD"),
  
  EURGBP("EURGBP"),
  
  EURJPY("EURJPY"),
  
  GBPJPY("GBPJPY"),
  
  EURCHF("EURCHF"),
  
  GBPCHF("GBPCHF"),
  
  EURCAD("EURCAD"),
  
  GBPCAD("GBPCAD"),
  
  AUDCAD("AUDCAD"),
  
  NZDCAD("NZDCAD"),
  
  AUDJPY("AUDJPY"),
  
  NZDJPY("NZDJPY"),
  
  AUDNZD("AUDNZD"),
  
  EURNZD("EURNZD"),
  
  GBPNZD("GBPNZD"),
  
  CADJPY("CADJPY"),
  
  CHFJPY("CHFJPY"),
  
  XAUUSD("XAUUSD"),
  
  XAGUSD("XAGUSD"),
  
  BTCUSD("BTCUSD"),
  
  ETHUSD("ETHUSD"),
  
  LTCUSD("LTCUSD"),
  
  XRPUSD("XRPUSD"),
  
  DAX30("DAX30"),
  
  SP500("SP500"),
  
  NAS100("NAS100"),
  
  UK100("UK100"),
  
  JPN225("JPN225"),
  
  AUS200("AUS200"),
  
  HK50("HK50"),
  
  US30("US30"),
  
  USOIL("USOil"),
  
  UKOIL("UKOil");

  private String value;

  SymbolEnum(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SymbolEnum fromValue(String value) {
    for (SymbolEnum b : SymbolEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    if (prefix == null) {
      prefix = "";
    }

    return String.format("%s=%s", prefix, this.toString());
  }

}

