openapi: 3.0.0
info:
  title: API interface
  version: 0.0.1

paths: { }

components:
  schemas:
    RandomUuid:
      description: Wrapper object for a random UUID
      type: object
      required:
        - uuid
      properties:
        uuid:
          type: string