services:

  nginx:
    container_name: middlenginx
    image: nginx:stable-alpine
    restart: on-failure
    expose:
      - "80"
      - "443:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ./matomo:/var/www/html:z,ro
      - ./nginx.middle.without.python.services.conf:/etc/nginx/conf.d/default.conf:rw
      #- ./matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
      #- ./nginx/certbot:/etc/letsencrypt
      #- ./certs/server.crt:/opt/nginx/conf/server.crt
      - ./certs/jdg.digital.pem:/opt/nginx/conf/jdg.digital.pem
    depends_on:
      #- certbot
      - keycloak

  keycloak:
    container_name: keycloak
    restart: on-failure
    build:
      context: ./keycloak
      args:
        KEYCLOAK_VERSION: 23.0.3
    env_file:
      - ./keycloak.dev.env
    ports:
      - "8180:8180"
      - "8443:8443"
    expose:
      - "8180"
      - "8443"
    volumes:
      - ./backup/keycloak/changelog.xml:/liquibase/changelog/changelog.xml
      - ./backup/keycloak/keycloak_data:/opt/jboss/keycloak/standalone/data
      - ./certs/jdg.digital.p12:/opt/keycloak/conf/jdg.digital.p12
      - ./certs/jdg.digital.p12:/etc/keystore/jdg.digital.p12
      - ./certs/jdg.digital.pem:/opt/keycloak/conf/jdg.digital.pem
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: on-failure
    env_file:
      - ./database.dev.env
    expose:
      - "6432" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - '6432:6432'
    volumes:
      - db:/var/lib/postgresql/data
      #- ./init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
    command: -p 6432

  apigateway:
    container_name: apigateway
    build: ./api-gateway
    restart: always
    expose:
      - '9080'
    ports:
      - "9080:9080"
    #volumes:
    #  - ./certs/server.crt:/opt/apigateway/conf/server.crt
    #  - ./certs/server.key:/opt/apigateway/conf/server.key
    depends_on:
      - "keycloak"

  javabackend:
    container_name: javabackend
    build: ./forex-backend-java
    restart: always
    expose:
      - '5080'
    ports:
      - "5080:5080"
    #volumes:
    #  - ./certs/server.crt:/opt/javabackend/conf/server.crt
    #  - ./certs/server.key:/opt/javabackend/conf/server.key
    depends_on:
      - "keycloak"

  forexfrontend:
    container_name: forexfrontend
    build:
      context: ./forex-frontend
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - "keycloak"

volumes:
  db:
    driver: local
  pgadmin-data:

networks:
  nginx-certbot: