services:

  nginx:
    container_name: middlenginx
    image: nginx:stable-alpine
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      #- ./matomo:/var/www/html:z,ro
      - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
      #- ./matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
    depends_on:
      - "keycloak"
      - "backend"
      - "tvsignals"

  keycloak:
    container_name: keycloak
    #image: quay.io/keycloak/keycloak:legacy
    image: quay.io/keycloak/keycloak:23.0.3
    restart: always
    env_file:
      - ./keycloak.dev.env
    volumes:
      - ./keycloak-themes/school/:/opt/jboss/keycloak/themes/school/
      - ./keycloak-themes/keywind/:/opt/jboss/keycloak/themes/keywind/
    command: |
      start-dev --http-port 8180
    ports:
      - "8180:8180"
    expose:
      - "8180"
    depends_on:
      - "db"

  backend:
    container_name: backend
    build: ./
    restart: on-failure
    ports:
      - "6081:6081"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/backend:/var/lib/backend
    depends_on:
      - "keycloak"

  javabackend:
    container_name: javabackend
    build: ./forex-backend-java
    restart: on-failure
    expose:
      - '8080'
    ports:
      - "8080:0080"
    #volumes:
    #  - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/backend:/var/lib/backend
    depends_on:
      - "keycloak"

  tvsignals:
    container_name: tvsignals
    build: ./tvsignals
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/backend:/var/lib/tvsignals
    depends_on:
      - "keycloak"

  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
        - ./database.dev.env
    expose:
      - "6432" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - '6432:6432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
    command: -p 6432

  forexfrontend:
    container_name: forexfrontend
    build:
      context: ./forex-frontend
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - "keycloak"


volumes:
  db:
    driver: local
  pgadmin-data: