version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=nobodysforex
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=trading-db
    expose:
      - "6432" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - '6432:6432'
    volumes:
      - db:/var/lib/postgresql/data
    command: -p 6432

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: goldi@goldi.com
      PGADMIN_DEFAULT_PASSWORD: r[MZ42\3dm^\
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - "db"

volumes:
  db:
    driver: local
  pgadmin-data: