services:

  nginx:
    container_name: middlenginx
    image: nginx:stable-alpine
    restart: on-failure
    links:
      - elasticsearch
      - kibana
    expose:
      - "80"
      - "443:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.middle.without.python.services.conf:/etc/nginx/conf.d/default.conf:rw
      - ./certs/certificate.pem:/etc/nginx/certificate.pem
      - ./certs/private.key:/etc/nginx/private.key
      - ./certs/passphrase.txt:/etc/nginx/passphrase.txt
    depends_on:
      #- keycloak
      - elasticsearch
      - kibana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    networks:
      - elk
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    volumes:
      #- 'esdata:/usr/share/elasticsearch/data'
      - esdata01:/usr/share/elasticsearch/data
      - ./elastisearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    networks:
      - elk
    volumes:
      - ./elastisearch/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    links:
      - elasticsearch

volumes:
  esdata:
  db:
    driver: local

networks:
  elk:
    driver: bridge

configs:
  qdrant_config:
    content: |
      log_level: INFO