services:

  nginx:
    container_name: middlenginx
    image: nginx:stable-alpine
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      #- ./matomo:/var/www/html:z,ro
      - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
      #- ./matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
    depends_on:
      - "keycloak"

  javabackend:
    container_name: javabackend
    build: ./forex-backend-java
    restart: always
    expose:
      - '8080'
    ports:
      - "8080:0080"
    #volumes:
    #  - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/backend:/var/lib/backend
    depends_on:
      - "keycloak"

  forexfrontend:
    container_name: forexfrontend
    build:
      context: ./forex-frontend
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - "keycloak"

volumes:
  db:
    driver: local
  pgadmin-data: