services:

  #nginx:
  #  container_name: middlenginx
  #  image: nginx:stable-alpine

  #  labels:
  #    co.elastic.logs/module: nginx
  #  expose:
  #    - "80"
  #    - "443:443"
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  volumes:
  #    - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
  #    - ./certs/certificate.pem:/etc/nginx/certificate.pem
  #    - ./certs/private.key:/etc/nginx/private.key
  #    - ./certs/passphrase.txt:/etc/nginx/passphrase.txt
    #depends_on:
    #  es01:
    #    condition: service_healthy
    #  kibana:
    #    condition: service_healthy
      #keycloak:
      #  condition: service_healthy
      #forexfrontend:
      #  condition: service_healthy

  #keycloak:
  #  container_name: keycloak
  #  restart: on-failure
  #  labels:
  #    co.elastic.logs/module: keycloak
  #  build:
  #    context: ./keycloak
  #    args:
  #      KEYCLOAK_VERSION: 23.0.3
  #  env_file:
  #    - ./keycloak.dev.env
  #  ports:
  #    - "8443:8443"
  #  expose:
  #    - "8443"
  #  volumes:
  #    - ./backup/keycloak/changelog.xml:/liquibase/changelog/changelog.xml
  #    - ./backup/keycloak/keycloak_data:/opt/jboss/keycloak/standalone/data
  #    - ./certs/jdg.digital.p12:/opt/jboss/keycloak/conf/jdg.digital.p12
  #    - ./certs/certificate.pem:/opt/jboss/keycloak/conf/certificate.pem
  #    - ./certs/private.key:/opt/jboss/keycloak/conf/private.key
  #  depends_on:
  #    - db
  #  #healthcheck:
  #  #  test: [ "CMD", "curl", "-kf", "https://keycloak:8443/realms/master" ]
  #  #  interval: 30s
  #  #  timeout: 10s
  #  #  retries: 3

  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: on-failure
    labels:
      co.elastic.logs/module: db
    env_file:
      - ./database.dev.env
    expose:
      - "6432" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - '6432:6432'
    volumes:
      - db:/var/lib/postgresql/data
      #- ./init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
    command: -p 6432

  #backend:
  #  container_name: backend
  #  build: ./
  #  restart: on-failure
  #  labels:
  #    co.elastic.logs/module: backend
  #  ports:
  #    - "6081:6081"
  #  volumes:
  #    - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/backend:/var/lib/backend
  #  depends_on:
  #    - keycloak

  #tvsignals:
  #  container_name: tvsignals
  #  build: ./tvsignals
  #  restart: on-failure
  #  labels:
  #    co.elastic.logs/module: tvsignals
  #  volumes:
  #    - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/backend:/var/lib/tvsignals
  #  depends_on:
  #    - keycloak

volumes:
  db:
    driver: local
