services:

  nginx:
    container_name: middlenginx
    image: nginx:stable-alpine
    restart: on-failure
    expose:
      - "80"
      - "443:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
      - ./certs/jdg.digital.pem:/opt/nginx/conf/jdg.digital.pem
    depends_on:
      - keycloak

  keycloak:
    container_name: keycloak
    restart: on-failure
    build:
      context: ./keycloak
      args:
        KEYCLOAK_VERSION: 23.0.3
    env_file:
      - ./keycloak.dev.env
    ports:
      - "8443:8443"
    expose:
      - "8443"
    volumes:
      - ./backup/keycloak/changelog.xml:/liquibase/changelog/changelog.xml
      - ./backup/keycloak/keycloak_data:/opt/jboss/keycloak/standalone/data
      - ./certs/jdg.digital.p12:/opt/jboss/keycloak/conf/jdg.digital.p12
      - ./certs/jdg.digital.p12:/etc/keystore/jdg.digital.p12
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: on-failure
    env_file:
      - ./database.dev.env
    expose:
      - "6432" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - '6432:6432'
    volumes:
      - db:/var/lib/postgresql/data
      #- ./init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
    command: -p 6432

  apigateway:
    container_name: apigateway
    build: ./api-gateway
    restart: always
    ports:
      - "9080:9080"
    volumes:
      - ./certs/jdg.digital.pem:/opt/apigateway/conf/jjdg.digital.pem
    depends_on:
      - keycloak

  javabackend:
    container_name: javabackend
    build: ./forex-backend-java
    restart: always
    ports:
      - "5080:5080"
    volumes:
      - ./certs/jdg.digital.pem:/opt/javabackend/conf/jdg.digital.pem
    depends_on:
      - keycloak

  forexfrontend:
    container_name: forexfrontend
    build:
      context: ./forex-frontend
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - keycloak

  backend:
    container_name: backend
    build: ./
    restart: always
    ports:
      - "6081:6081"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/backend:/var/lib/backend
    depends_on:
      - keycloak

  tvsignals:
    container_name: tvsignals
    build: ./tvsignals
    restart: always
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/backend:/var/lib/tvsignals
    depends_on:
      - keycloak

volumes:
  db:
    driver: local