services:

  nginx:
    container_name: middlenginx
    image: nginx:stable-alpine
    restart: on-failure
    expose:
      - "80"
      - "443:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ./matomo:/var/www/html:z,ro
      - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
      #- ./matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
      #- ./nginx/certbot:/etc/letsencrypt
      - ./certs/server.crt:/opt/nginx/conf/server.crt
      - ./certs/server.key:/opt/nginx/conf/server.key
    depends_on:
      #- certbot
      - keycloak

  #certbot:
  #  image: certbot/certbot
  #  volumes:
  #    - ./nginx/certbot:/etc/letsencrypt
  #  entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  keycloak:
    container_name: keycloak
    build:
      context: ./keycloak
      args:
        KEYCLOAK_VERSION: 23.0.3
    #command: [ "start", "--optimized", "--http-port 8180", "--log-level=ERROR",  "--hostname-strict-https=false", "--hostname-url='https://85.215.32.163:8180/realms/master'" ]
    #
    #start-dev --http-port 8180 --log-level=ERROR
    command: |
      start --optimized --http-port 8180 --log-level=INFO --hostname-url="https://85.215.32.163:8443" --https-certificate-file=/opt/keycloak/conf/server.crt --https-certificate-key-file=/opt/keycloak/conf/server.key
    depends_on:
      - db
    environment:
      - ./keycloak.dev.env
    ports:
      - "8180:8180"
      - "8443:8443"
    expose:
      - "8180"
      - "8443"
    volumes:
      - ./backup/keycloak/changelog.xml:/liquibase/changelog/changelog.xml
      - ./backup/keycloak/keycloak_data:/opt/jboss/keycloak/standalone/data
      - ./certs/server.crt:/opt/keycloak/conf/server.crt
      - ./certs/server.key:/opt/keycloak/conf/server.key

  #keycloak:
  #  container_name: keycloak
  #  image: quay.io/keycloak/keycloak:23.0.3
  #  #restart: on-failure
  #  env_file:
  #    - ./keycloak.dev.env
  #  volumes:
  #    - ./keycloak-themes/school/:/opt/jboss/keycloak/themes/school/
  #    - ./keycloak-themes/keywind/:/opt/jboss/keycloak/themes/keywind/
  #    - ./certs/server.crt:/opt/jboss/keycloak/conf/server.crt
  #    - ./certs/server.key:/opt/jboss/keycloak/conf/server.key
  #    #- /certs/:/etc/x509/https"
  #  command: |
  #    start --optimized --http-port 8180 --log-level=ERROR --hostname-strict-https=false --hostname-url="https://85.215.32.163:8180/realms/master"
  #  ports:
  #    - "8180:8180"
  #    - "8443:8443"
  #  expose:
  #    - "8180"
  #    - "8443"
  #  depends_on:
  #    - "db"

  db:
    image: postgres:14.1-alpine
    restart: on-failure
    env_file:
      - ./database.dev.env
    expose:
      - "6432" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - '6432:6432'
    volumes:
      - db:/var/lib/postgresql/data
      #- ./init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
    command: -p 6432

  javabackend:
    container_name: javabackend
    build: ./forex-backend-java
    restart: always
    expose:
      - '5080'
    ports:
      - "5080:5080"
    #volumes:
    #  - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/backend:/var/lib/backend
    depends_on:
      - "keycloak"

  forexfrontend:
    container_name: forexfrontend
    build:
      context: ./forex-frontend
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - "keycloak"

  backend:
    container_name: backend
    build: ./
    restart: always
    ports:
      - "6081:6081"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/backend:/var/lib/backend
    depends_on:
      - "keycloak"

  tvsignals:
    container_name: tvsignals
    build: ./tvsignals
    restart: always
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/backend:/var/lib/tvsignals
    depends_on:
      - "keycloak"

volumes:
  db:
    driver: local
  pgadmin-data:

networks:
  nginx-certbot: