services:

  #nginx:
  #  container_name: middlenginx
  #  image: nginx:stable-alpine

  #  labels:
  #    co.elastic.logs/module: nginx
  #  expose:
  #    - "80"
  #    - "443:443"
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  volumes:
  #    - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
  #    - ./certs/certificate.pem:/etc/nginx/certificate.pem
  #    - ./certs/private.key:/etc/nginx/private.key
  #    - ./certs/passphrase.txt:/etc/nginx/passphrase.txt
    #depends_on:
    #  es01:
    #    condition: service_healthy
    #  kibana:
    #    condition: service_healthy
      #keycloak:
      #  condition: service_healthy
      #forexfrontend:
      #  condition: service_healthy

  #keycloak:
  #  container_name: keycloak
  #  restart: on-failure
  #  labels:
  #    co.elastic.logs/module: keycloak
  #  build:
  #    context: ./keycloak
  #    args:
  #      KEYCLOAK_VERSION: 23.0.3
  #  env_file:
  #    - ./keycloak.dev.env
  #  ports:
  #    - "8443:8443"
  #  expose:
  #    - "8443"
  #  volumes:
  #    - ./backup/keycloak/changelog.xml:/liquibase/changelog/changelog.xml
  #    - ./backup/keycloak/keycloak_data:/opt/jboss/keycloak/standalone/data
  #    - ./certs/jdg.digital.p12:/opt/jboss/keycloak/conf/jdg.digital.p12
  #    - ./certs/certificate.pem:/opt/jboss/keycloak/conf/certificate.pem
  #    - ./certs/private.key:/opt/jboss/keycloak/conf/private.key
  #  depends_on:
  #    - db
  #  #healthcheck:
  #  #  test: [ "CMD", "curl", "-kf", "https://keycloak:8443/realms/master" ]
  #  #  interval: 30s
  #  #  timeout: 10s
  #  #  retries: 3

  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: on-failure
    labels:
      co.elastic.logs/module: db
    env_file:
      - ./database.dev.env
    expose:
      - "6432" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - '6432:6432'
    volumes:
      - db:/var/lib/postgresql/data
      #- ./init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
    command: -p 6432

  #apigateway:
  #  container_name: apigateway
  #  build: ./api-gateway
  #  restart: always
  #  labels:
  #    co.elastic.logs/module: api-gateway
  #    co.elastic.logs/json.keys_under_root: "true"
  #    co.elastic.logs/json.overwrite_keys: "true"
  #    co.elastic.logs/json.expand_keys: "true"
  #    co.elastic.logs/json.message_key: "message"
  #    co.elastic.logs/json.add_error_key: "true"
  #  ports:
  #    - "9080:9080"
  #javabackend:
  #  container_name: javabackend
  #  build: ./forex-backend-java
  #  restart: always
  #  labels:
  #    co.elastic.logs/module: forex-backend-java
  #    co.elastic.logs/json.keys_under_root: "true"
  #    co.elastic.logs/json.overwrite_keys: "true"
  #    co.elastic.logs/json.expand_keys: "true"
  #    co.elastic.logs/json.message_key: "message"
  #    co.elastic.logs/json.add_error_key: "true"
  #  ports:
  #    - "5080:5080"


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafkaserver
    restart: on-failure
    labels:
      co.elastic.logs/module: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092

  #tvsignals:
  #  container_name: tvsignals
  #  build: ./tvsignals
  #  restart: always
  #  labels:
  #    co.elastic.logs/module: tvsignals
  #  ports:
  #    - "80:80"


volumes:
  db:
    driver: local
