services:

  nginx:
    container_name: middlenginx
    image: nginx:stable-alpine
    restart: on-failure
    expose:
      - "80"
      - "443:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.middle.without.python.services.conf:/etc/nginx/conf.d/default.conf:rw
      - ./certs/jdg.digital.pem:/opt/nginx/conf/jdg.digital.pem
    depends_on:
      - keycloak

  keycloak:
    container_name: keycloak
    restart: on-failure
    build:
      context: ./keycloak
      args:
        KEYCLOAK_VERSION: 23.0.3
    environment:
      KEYCLOAK_USER: keycloak_hero
      KEYCLOAK_PASSWORD: 8rjFab9E8r13
      KEYCLOAK_HEALTH_ENABLED: true
      KEYCLOAK_METRICS_ENABLED: true
      KEYCLOAK_SPI_THEME_DEFAULT: keycloak
      KEYCLOAK_LOGLEVEL: DEBUG
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 8rjFab9E8r13
      DEBUG: true
      #DEBUG_PORT: '*:8787'
      DB_VENDOR: postgres
      DB_ADDR: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 6432
      KC_DB_SCHEMA: keycloak
      DB_USER: nobodysforex
      DB_PASSWORD: pwd
      TZ: Europe/Paris
      KC_HOSTNAME_URL: https://172.25.138.181:8443
      KC_HEALTH_ENABLED: true
      KC_DB_URL: jdbc:postgresql://db:6432/trading-db
      KC_HTTPS_KEY_STORE_FILE: /opt/jboss/keycloak/conf/jdg.digital.p12
      KC_HTTPS_KEY_STORE_PASSWORD: Blade1708
      KC_HTTPS_KEY_STORE_TYPE: PKCS12
    ports:
      - "8443:8443"
    expose:
      - "8443"
    volumes:
      - ./backup/keycloak/changelog.xml:/liquibase/changelog/changelog.xml
      - ./backup/keycloak/keycloak_data:/opt/jboss/keycloak/standalone/data
      - ./certs/jdg.digital.p12:/opt/jboss/keycloak/conf/jdg.digital.p12
      - ./certs/jdg.digital.p12:/etc/keystore/jdg.digital.p12
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: on-failure
    env_file:
      - ./database.dev.env
    expose:
      - "6432" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - '6432:6432'
    volumes:
      - db:/var/lib/postgresql/data
      #- ./init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
    command: -p 6432

  #apigateway:
  #  container_name: apigateway
  #  build: ./api-gateway
  #  restart: always
  #  ports:
  #    - "9080:9080"
  #  volumes:
  #    - ./certs/jdg.digital.pem:/opt/apigateway/conf/jjdg.digital.pem
  #  depends_on:
  #    - keycloak

  javabackend:
    container_name: javabackend
    build: ./forex-backend-java
    restart: always
    ports:
      - "5080:5080"
    volumes:
      - ./certs/jdg.digital.pem:/opt/javabackend/conf/jdg.digital.pem
    depends_on:
      - keycloak

  #forexfrontend:
  #  container_name: forexfrontend
  #  build:
  #    context: ./forex-frontend
  #    dockerfile: ./Dockerfile
  #  volumes:
  #    - .:/usr/app/
  #    - /usr/app/node_modules
  #  depends_on:
  #    - keycloak

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    #expose:
    #  - 6333
    #  - 6334
    #  - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant_data

volumes:
  db:
    driver: local

configs:
  qdrant_config:
    content: |
      log_level: INFO