services:

  nginx:
    container_name: middlenginx
    image: nginx:stable-alpine
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      #- ./matomo:/var/www/html:z,ro
      - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
      #- ./matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
    depends_on:
      - "backend"
      - "tvsignals"

  backend:
    container_name: backend
    build: ./
    restart: on-failure
    ports:
      - "6081:6081"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/backend:/var/lib/backend
    depends_on:
      - "db"

  javabackend:
    container_name: javabackend
    build: ./forex-backend-java
    restart: on-failure
    expose:
      - '8080'
    ports:
      - "8080:0080"
    #volumes:
    #  - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/backend:/var/lib/backend
    depends_on:
      - "db"

  tvsignals:
    container_name: tvsignals
    build: ./tvsignals
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/backend:/var/lib/tvsignals
    depends_on:
      - "db"

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=nobodysforex
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=trading-db
    expose:
      - "6432" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - '6432:6432'
    volumes:
      - db:/var/lib/postgresql/data
    command: -p 6432

  forexfrontend:
    container_name: forexfrontend
    build:
      context: ./forex-frontend
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules


volumes:
  db:
    driver: local
  pgadmin-data: