server:
  port: 9080
  forward-headers-strategy: framework
  #servlet:
  #  context-path: /resource-server
  servlet:
    session:
      timeout: 1m

spring:
  datasource:
    url: jdbc:postgresql://172.31.138.212:6432/vaadin
    username: nobodysforex
    password: pwd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://172.25.141.161:8443/realms/forex-frontend-vaadin
            jwk-set-uri: https://172.25.141.161:8443/realms/forex-frontend-vaadin/protocol/openid-connect/certs
            token-uri: https://172.25.141.161:8443/realms/oauth2/v1/token
        registration:
          keycloak:
            client-id: forex-frontend-vaadin-client
            client-secret: bmKLy4YdvepYASGrRmNndm6DbKyft69M
            scope:
              - profile
              - email
              - openid
              - roles


logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

vaadin:
  # Reduce the heartbeat interval so that we get multiple ones before the session times out
  heartbeatInterval: 10
  # Don't let the heartbeat keep the sessions alive indefinitely
  closeIdleSessions: true