server:
  port: 9080
  forward-headers-strategy: framework
  #servlet:
  #  context-path: /resource-server
  servlet:
    session:
      timeout: 1m

spring:
  datasource:
    url: jdbc:postgresql://172.31.138.212:6432/vaadin
    username: nobodysforex
    password: pwd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://172.31.138.212:8443/realms/webinar
        registration:
          keycloak:
            client-id: webinar-sample-app
            client-secret: se8wtanzEr3g13vJVLBF8MOhW6JSzaQl
            scope:
              - profile
              - email
              - openid
              - roles


logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

vaadin:
  # Reduce the heartbeat interval so that we get multiple ones before the session times out
  heartbeatInterval: 10
  # Don't let the heartbeat keep the sessions alive indefinitely
  closeIdleSessions: true