server:
  port: 9080
  forward-headers-strategy: framework
  error:
    include-stacktrace: ON_PARAM
  cors:
    allowOrigins
  servlet:
    context-path: /api
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/services.p12
    key-store-password: Blade1708
    key-alias: services

logging:
  level:
    root: info
