server:
  port: 9080
  forward-headers-strategy: framework
  error:
    include-stacktrace: ON_PARAM
  servlet:
    context-path: /api

logging:
  level:
    root: info

forex:
  data:
    service:
      url: http://localhost:5080/forex

spring:
  kafka:
    bootstrap-servers: 172.31.138.212:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: forex #group-id is the name of the consumer group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer