server:
  port: 9080
  forward-headers-strategy: framework
  error:
    include-stacktrace: ON_PARAM
  servlet:
    context-path: /api

logging:
  level:
    root: debug


forex:
  data:
    service:
      url: http://localhost:5080/forex