/**
 * API interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StrategyEnum } from './strategy-enum';
import { TradeTypeEnum } from './trade-type-enum';
import { SymbolEnum } from './symbol-enum';
import { TimeFrameEnum } from './time-frame-enum';

export interface Signal {
    symbol: SymbolEnum;
    strategy?: StrategyEnum;
    type?: TradeTypeEnum;
    entry?: number;
    sl?: number;
    tp?: number;
    ignrored?: boolean;
    ignroredMessage?: string;
}
export namespace Trade {
}


