/**
 * API interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StrategyEnum } from './strategy-enum';
import { SymbolEnum } from './symbol-enum';
import { TimeFrameEnum } from './time-frame-enum';


export interface StatsPerProdTrade { 
    id?: number;
    symbol: SymbolEnum;
    timeframe: TimeFrameEnum;
    strategy: StrategyEnum;
    stamp?: Date;
    prodWins?: number;
    prodLoses?: number;
    prodTotal?: number;
    prodWinPercentage?: number;
    devWins?: number;
    devLoses?: number;
    devTotal?: number;
    devWinPercentage?: number;
}
export namespace StatsPerProdTrade {
}


