/**
 * API interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SymbolEnum = 'AUDCHF' | 'EURUSD' | 'GBPUSD' | 'USDJPY' | 'USDCHF' | 'USDCAD' | 'AUDUSD' | 'NZDUSD' | 'EURGBP' | 'EURJPY' | 'GBPJPY' | 'EURCHF' | 'GBPCHF' | 'EURCAD' | 'GBPCAD' | 'AUDCAD' | 'NZDCAD' | 'AUDJPY' | 'NZDJPY' | 'AUDNZD' | 'EURNZD' | 'GBPNZD' | 'CADJPY' | 'CHFJPY' | 'XAUUSD' | 'XAGUSD' | 'BTCUSD' | 'ETHUSD' | 'LTCUSD' | 'XRPUSD' | 'DAX30' | 'SP500' | 'NAS100' | 'UK100' | 'JPN225' | 'AUS200' | 'HK50' | 'US30' | 'USOil' | 'UKOil';

export const SymbolEnum = {
    Audchf: 'AUDCHF' as SymbolEnum,
    Eurusd: 'EURUSD' as SymbolEnum,
    Gbpusd: 'GBPUSD' as SymbolEnum,
    Usdjpy: 'USDJPY' as SymbolEnum,
    Usdchf: 'USDCHF' as SymbolEnum,
    Usdcad: 'USDCAD' as SymbolEnum,
    Audusd: 'AUDUSD' as SymbolEnum,
    Nzdusd: 'NZDUSD' as SymbolEnum,
    Eurgbp: 'EURGBP' as SymbolEnum,
    Eurjpy: 'EURJPY' as SymbolEnum,
    Gbpjpy: 'GBPJPY' as SymbolEnum,
    Eurchf: 'EURCHF' as SymbolEnum,
    Gbpchf: 'GBPCHF' as SymbolEnum,
    Eurcad: 'EURCAD' as SymbolEnum,
    Gbpcad: 'GBPCAD' as SymbolEnum,
    Audcad: 'AUDCAD' as SymbolEnum,
    Nzdcad: 'NZDCAD' as SymbolEnum,
    Audjpy: 'AUDJPY' as SymbolEnum,
    Nzdjpy: 'NZDJPY' as SymbolEnum,
    Audnzd: 'AUDNZD' as SymbolEnum,
    Eurnzd: 'EURNZD' as SymbolEnum,
    Gbpnzd: 'GBPNZD' as SymbolEnum,
    Cadjpy: 'CADJPY' as SymbolEnum,
    Chfjpy: 'CHFJPY' as SymbolEnum,
    Xauusd: 'XAUUSD' as SymbolEnum,
    Xagusd: 'XAGUSD' as SymbolEnum,
    Btcusd: 'BTCUSD' as SymbolEnum,
    Ethusd: 'ETHUSD' as SymbolEnum,
    Ltcusd: 'LTCUSD' as SymbolEnum,
    Xrpusd: 'XRPUSD' as SymbolEnum,
    Dax30: 'DAX30' as SymbolEnum,
    Sp500: 'SP500' as SymbolEnum,
    Nas100: 'NAS100' as SymbolEnum,
    Uk100: 'UK100' as SymbolEnum,
    Jpn225: 'JPN225' as SymbolEnum,
    Aus200: 'AUS200' as SymbolEnum,
    Hk50: 'HK50' as SymbolEnum,
    Us30: 'US30' as SymbolEnum,
    UsOil: 'USOil' as SymbolEnum,
    UkOil: 'UKOil' as SymbolEnum
};

