/**
 * API interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TimeFrameEnum = 'M1' | 'M5' | 'M15' | 'M30' | 'H1' | 'H4' | 'D1' | 'W1' | 'MN1';

export const TimeFrameEnum = {
    M1: 'M1' as TimeFrameEnum,
    M5: 'M5' as TimeFrameEnum,
    M15: 'M15' as TimeFrameEnum,
    M30: 'M30' as TimeFrameEnum,
    H1: 'H1' as TimeFrameEnum,
    H4: 'H4' as TimeFrameEnum,
    D1: 'D1' as TimeFrameEnum,
    W1: 'W1' as TimeFrameEnum,
    Mn1: 'MN1' as TimeFrameEnum
};

