/**
 * API interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StrategyEnum } from './strategy-enum';
import { SymbolEnum } from './symbol-enum';


/**
 * Trade statistics
 */
export interface TradeStat { 
    symbol: SymbolEnum;
    strategy: StrategyEnum;
    wins: number;
    loses: number;
    total: number;
    winpercentage: number;
    profit: number;
}
export namespace TradeStat {
}


