/**
 * API interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SymbolEnum } from './symbol-enum';


export interface TradeHistoryUpdate { 
    symbol: SymbolEnum;
    closed?: string;
    magic?: number;
    profit?: number;
    swap?: number;
    commision?: number;
    exit?: number;
}
export namespace TradeHistoryUpdate {
}


