openapi: 3.0.0
info:
  title: API interface
  version: 0.0.1

paths: { }

components:
  schemas:

    TimeFrameEnum:
      type: string
      enum:
        - M1
        - M5
        - M15
        - M30
        - H1
        - H4
        - D1
        - W1
        - MN1

    SymbolEnum:
      type: string
      enum:
        - AUDCHF
        - EURUSD
        - GBPUSD
        - USDJPY
        - USDCHF
        - USDCAD
        - AUDUSD
        - NZDUSD
        - EURGBP
        - EURJPY
        - GBPJPY
        - EURCHF
        - GBPCHF
        - EURCAD
        - GBPCAD
        - AUDCAD
        - NZDCAD
        - AUDJPY
        - NZDJPY
        - AUDNZD
        - EURNZD
        - GBPNZD
        - CADJPY
        - CHFJPY
        - XAUUSD
        - XAGUSD
        - BTCUSD
        - ETHUSD
        - LTCUSD
        - XRPUSD
        - DAX30
        - SP500
        - NAS100
        - UK100
        - JPN225
        - AUS200
        - HK50
        - US30
        - USOil
        - UKOil

    StrategyEnum:
      type: string
      enum:
        - AI Volume Supertrend-WMA
        - AI Volume Supertrend-WMA_WITHOUT_REG
        - STD-Filtered-Close
        - STD-Filtered-Close_WITHOUT_REG
        - SuperTrend AI
        - SuperTrend AI_WITHOUT_REG
        - NNR
        - NNR_WITHOUT_REG
        - Super_AI_Trend
        - Super_AI_Trend_WITHOUT_REG
        - 70%_Strategy
        - SSL_Hybrid
        - SSL_Hybrid_WITHOUT_REG
        - AI_VOLUME_SUPERTREND
        - SSL_+_Wave_Trend_Strategy
        - VHMA
        - VHMA_WITHOUT_REG
        - T3Fvma
        - T3Fvma_WITHOUT_REG
        - SentimentRangeMa
        - SentimentRangeMa_WITHOUT_REG
        - GaussianChannelTrendAI
        - GaussianChannelTrendAI_WITHOUT_REG
        - T3_LocallyWeightedRegression
        - T3_LocallyWeightedRegression_WITHOUT_REG
        - T3_HmaKahlman
        - T3_HmaKahlman_WITHOUT_REG
        - T3_JMaCrossover
        - T3_JMaCrossover_WITHOUT_REG
        - T3_MachineLearningLogisticRegression
        - T3_MachineLearningLogisticRegression_WITHOUT_REG
        - T3_GapFilling
        - T3_GapFilling_WITHOUT_REG
        - T3_EvwmaVwapMacd
        - T3_EvwmaVwapMacd_WITHOUT_REG
        - T3_BollingerBandsPinbar
        - T3_BollingerBandsPinbar_WITHOUT_REG
        - T3_TrendAI
        - T3_TrendAI_WITHOUT_REG
        - T3_NNFX
        - T3_NNFX_WITHOUT_REG
        - T3_EfficientTrendStepMod
        - T3_EfficientTrendStepMod_WITHOUT_REG
        - T3_AroonBased
        - T3_AroonBased_WITHOUT_REG
        - T3_EmaStrategy
        - T3_EmaStrategy_WITHOUT_REG
        - SOTT_Lorentzian
        - SOTT_Lorentzian_WITHOUT_REG
        - RSS_WMA
        - RSS_WMA_WITHOUT_WITHOUT_REG
        - T3_MesaPhasor
        - T3_MesaPhasor_WITHOUT_REG
        - T3_SupportAndResistanceLevels
        - T3_SupportAndResistanceLevels_WITHOUT_REG
        - T3_Eams
        - T3_EAMS_WITHOUT_REG
        - T3_VolumeDifferenceDeltaCycleOscillator
        - T3_VolumeDifferenceDeltaCycleOscillator_WITHOUT_REG
        - T3_MacdScalp
        - T3_MacdScalp_WITHOUT_REG
        - T3_DiCrossingDaily
        - T3_DiCrossingDaily_WITHOUT_REG
        - T3_HalfTrend
        - T3_HalfTrend_WITHOUT_REG
        - T3_BernoulliEntropyFunction
        - T3_BernoulliEntropyFunction_WITHOUT_REG
        - T3_LinearTrend
        - T3_LinearTrend_WITHOUT_REG
        - T3_UtBot
        - T3_UtBot_WITHOUT_REG
        - T3_PivotPointSuperTrend
        - T3_PivotPointSuperTrend_WITHOUT_REG
        - T3_AntiBreakout
        - T3_AntiBreakout_WITHOUT_REG
        - T3_Lube
        - T3_Lube_WITHOUT_REG
        - T3_ThirdWave
        - T3_ThirdWave_WITHOUT_REG
        - T3_PinBarStrategy
        - T3_PinBarStrategy_WITHOUT_REG
        - T3_ReversalFinder
        - T3_ReversalFinder_WITHOUT_REG
        - T3_MacdHistogram_LLTDEMA
        - T3_MacdHistogram_LLTDEMA_WITHOUT_REG
        - T3_MacdHistogram_TDEMA
        - T3_MacdHistogram_TDEMA_WITHOUT_REG
        - T3_MacdHistogram_DEMA
        - T3_MacdHistogram_DEMA_WITHOUT_REG
        - T3_MacdHistogram_EMA
        - T3_MacdHistogram_EMA_WITHOUT_REG
        - T3_MacdHistogram_THMA
        - T3_MacdHistogram_THMA_WITHOUT_REG
        - T3_MacdHistogram_ZLEMA
        - T3_MacdHistogram_ZLEMA_WITHOUT_REG
        - T3vMacdHistogram_ZLTEMA
        - T3_MacdHistogram_ZLTEMA_WITHOUT_REG
        - T3_NeutronixAi
        - T3_NeutronixAi_WITHOUT_REG
        - T3_NeutronixSwing
        - T3_NeutronixSwing_WITHOUT_REG
        - T3_NeutronixScalping
        - T3_NeutronixScalping_WITHOUT_REG
        - T3_ThreeCommasBotStrategy_EMA
        - T3_ThreeCommasBotStrategy_EMA_WITHOUT_REG
        - T3_ThreeCommasBotStrategy_HEMA
        - T3_ThreeCommasBotStrategy_HEMA_WITHOUT_REG
        - T3_ThreeCommasBotStrategy_SMA
        - T3_ThreeCommasBotStrategy_SMA_WITHOUT_REG
        - T3_ThreeCommasBotStrategy_HMA
        - T3_ThreeCommasBotStrategy_HMA_WITHOUT_REG
        - T3_ThreeCommasBotStrategy_WMA
        - T3_ThreeCommasBotStrategy_WMA_WITHOUT_REG
        - T3_ThreeCommasBotStrategy_DEMA
        - T3_ThreeCommasBotStrategy_DEMA_WITHOUT_REG
        - T3_ThreeCommasBotStrategy_VWMA
        - T3_ThreeCommasBotStrategy_VWMA_WITHOUT_REG
        - T3_ThreeCommasBotStrategy_VWAP
        - T3_ThreeCommasBotStrategy_VWAP_WITHOUT_REG
        - T3_ThreeCommasBotStrategy_T3
        - T3_ThreeCommasBotStrategy_T3_WITHOUT_REG
        - T3_MomentumBasedZigZag
        - T3_MomentumBasedZigZag_WITHOUT_REG
        - T3_DekidakaAshiSignals
        - T3_DekidakaAshiSignals_WITHOUT_REG
        - T3_SuperTrendCleaned
        - T3_SuperTrendCleaned_WITHOUT_REG
        - T3_ScaledNormalizedVector
        - T3_ScaledNormalizedVector_WITHOUT_REG
        - T3_RangeFilters
        - T3_RangeFilters_WITHOUT_REG
        - T3_NeutronixDCAemu
        - T3_NeutronixDCAemu_WITHOUT_REG
        - T3_UhlMASystem
        - T3_UhlMASystem_WITHOUT_REG
        - T3_LlorensActivator
        - T3_LlorensActivator_WITHOUT_REG
        - T3_CustomSuperTrendCleaned
        - T3_CustomSuperTrendCleaned_WITHOUT_REG
        - T3_BilateralStochasticOscillator
        - T3_BilateralStochasticOscillator_WITHOUT_REG
        - T3_NickRypockTrailingReverse
        - T3_NickRypockTrailingReverse_WITHOUT_REG
        - T3_GridLike
        - T3_GridLike_WITHOUT_REG
        - AdxCrossover_M15
        - AdxCrossover_H1
        - AdxCrossover_H4
        - ADXEMA14_M15
        - ADXEMA14_H1
        - ADXEMA14_H4
        - AdxRsi_M15
        - AdxRsi_H1
        - AdxRsi_H4
        - AroonAdx_M15
        - AroonAdx_H1
        - AroonAdx_H4
        - AroonIndicator_M15
        - AroonIndicator_H1
        - AroonIndicator_H4
        - AwesomeOscillator_M15
        - AwesomeOscillator_H1
        - AwesomeOscillator_H4
        - AwesomeOscillatorSaucer_M15
        - AwesomeOscillatorSaucer_H1
        - AwesomeOscillatorSaucer_H4
        - BladeRunner_M15
        - BladeRunner_H1
        - BladeRunner_H4
        - BollingerBandsAndRSI_M15
        - BollingerBandsAndRSI_H1
        - BollingerBandsAndRSI_H4
        - BollingerBandsAndRSI2_M15
        - BollingerBandsAndRSI2_H1
        - BollingerBandsAndRSI2_H4
        - CciMacdPsar_M15
        - CciMacdPsar_H1
        - CciMacdPsar_H4
        - CciMovingAverage_M15
        - CciMovingAverage_H1
        - CciMovingAverage_H4
        - CommodityChannelIndex_M15
        - CommodityChannelIndex_H1
        - CommodityChannelIndex_H4
        - DonchianATR_M15
        - DonchianATR_H1
        - DonchianATR_H4
        - DonchianBreakout_M15
        - DonchianBreakout_H1
        - DonchianBreakout_H4
        - DonchianMiddle_M15
        - DonchianMiddle_H1
        - DonchianMiddle_H4
        - DpoCandlestick_M15
        - DpoCandlestick_H1
        - DpoCandlestick_H4
        - ElderRay_M15
        - ElderRay_H1
        - ElderRay_H4
        - ElderRayAlternative_M15
        - ElderRayAlternative_H1
        - ElderRayAlternative_H4
        - ThreeEma_M15
        - ThreeEma_H1
        - ThreeEma_H4
        - ThreeEmaAlternative_M15
        - ThreeEmaAlternative_H1
        - ThreeEmaAlternative_H4
        - EMACrossover_M15
        - EMACrossover_H1
        - EMACrossover_H4
        - EMACrossoverAlternative_M15
        - EMACrossoverAlternative_H1
        - EMACrossoverAlternative_H4
        - EMACrossoverRSI_M15
        - EMACrossoverRSI_H1
        - EMACrossoverRSI_H4
        - EMACrossoverRSIAlternative_M15
        - EMACrossoverRSIAlternative_H1
        - EMACrossoverRSIAlternative_H4
        - EMAMACDRSI_M15
        - EMAMACDRSI_H1
        - EMAMACDRSI_H4
        - EMAMI_M15
        - EMAMI_H1
        - EMAMI_H4
        - ForceIndexEMA_M15
        - ForceIndexEMA_H1
        - ForceIndexEMA_H4
        - KeltnerStochasticAdx_M15
        - KeltnerStochasticAdx_H1
        - KeltnerStochasticAdx_H4
        - KAMA_M15
        - KAMA_H1
        - KAMA_H4
        - KAMACrossover_M15
        - KAMACrossover_H1
        - KAMACrossover_H4
        - KeltnerAdx_M15
        - KeltnerAdx_H1
        - KeltnerAdx_H4
        - KeltnerRsi_M15
        - KeltnerRsi_H1
        - KeltnerRsi_H4
        - KeltnerStochastic_M15
        - KeltnerStochastic_H1
        - KeltnerStochastic_H4
        - MACDCrossover_M15
        - MACDCrossover_H1
        - MACDCrossover_H4
        - MACDHistogramReversal_M15
        - MACDHistogramReversal_H1
        - MACDHistogramReversal_H4
        - MacdRsiSma_M15
        - MacdRsiSma_H1
        - MacdRsiSma_H4
        - MACDStochasticCrossover_M15
        - MACDStochasticCrossover_H1
        - MACDStochasticCrossover_H4
        - MACDZeroCross_M15
        - MACDZeroCross_H1
        - MACDZeroCross_H4
        - MFI_M15
        - MFI_H1
        - MFI_H4
        - OopsSignals_M15
        - OopsSignals_H1
        - OopsSignals_H4
        - PsarMovingAverage_M15
        - PsarMovingAverage_H1
        - PsarMovingAverage_H4
        - Rsi2_M15
        - Rsi2_H1
        - Rsi2_H4
        - Rsi8020_M15
        - Rsi8020_H1
        - Rsi8020_H4
        - SimpleMAExponentialMA_M15
        - SimpleMAExponentialMA_H1
        - SimpleMAExponentialMA_H4
        - SimpleMAExponentialMAAlternative_M15
        - SimpleMAExponentialMAAlternative_H1
        - SimpleMAExponentialMAAlternative_H4
        - SMAMI_M15
        - SMAMI_H1
        - SMAMI_H4
        - StochasticOscillatorNoExit_M15
        - StochasticOscillatorNoExit_H1
        - StochasticOscillatorNoExit_H4
        - TripleBollingerBands_M15
        - TripleBollingerBands_H1
        - TripleBollingerBands_H4
        - TrixEma_M15
        - TrixEma_H1
        - TrixEma_H4
        - TrixMI_M15
        - TrixMI_H1
        - TrixMI_H4
        - TrixRsi_M15
        - TrixRsi_H1
        - TrixRsi_H4
        - TSICrossover_M15
        - TSICrossover_H1
        - TSICrossover_H4
        - VortexCrossover_M15
        - VortexCrossover_H1
        - VortexCrossover_H4
        - VortexSma_M15
        - VortexSma_H1
        - VortexSma_H4
        - WilliamsIndicator_M15
        - WilliamsIndicator_H1
        - WilliamsIndicator_H4
        - WilliamsRsi_M15
        - WilliamsRsi_H1
        - WilliamsRsi_H4
        - WilliamsStochastic_M15
        - WilliamsStochastic_H1
        - WilliamsStochastic_H4
        - ZigZag_M15
        - ZigZag_H1
        - ZigZag_H4
        - EMACrossoverMACD_M15
        - EMACrossoverMACD_H1
        - EMACrossoverMACD_H4

    TradeTypeEnum:
      type: string
      enum:
        - BUY
        - SELL

    TradeStat:
      description: Trade statistics
      type: object
      required:
        - symbol
        - strategy
        - wins
        - loses
        - total
        - winpercentage
        - profit
      properties:
        symbol:
          $ref: '#/components/schemas/SymbolEnum'
        strategy:
          $ref: '#/components/schemas/StrategyEnum'
        wins:
          type: integer
        loses:
          type: integer
        total:
          type: integer
        winpercentage:
          type: number
        profit:
          type: number

    Trade:
      type: object
      required:
        - symbol
        - timeframe
        - strategy
      properties:
        id:
          type: integer
        symbol:
          $ref: '#/components/schemas/SymbolEnum'
        timeframe:
          $ref: '#/components/schemas/TimeFrameEnum'
        strategy:
          $ref: '#/components/schemas/StrategyEnum'
        type:
          $ref: '#/components/schemas/TradeTypeEnum'
        entry:
          type: number
        exit:
          type: number
        profit:
          type: number
        closed:
          type: string
          format: date-time
        activated:
          type: string
          format: date-time

    TradeHistoryUpdate:
      type: object
      required:
        - symbol
      properties:
        symbol:
          $ref: '#/components/schemas/SymbolEnum'
        closed:
          type: string
        magic:
          type: integer
        profit:
          type: number
        swap:
          type: number
        commision:
          type: number
        exit:
          type: number

    StatsPerProdTrade:
      type: object
      required:
        - symbol
        - timeframe
        - strategy
      properties:
        id:
          type: number
        symbol:
          $ref: '#/components/schemas/SymbolEnum'
        timeframe:
          $ref: '#/components/schemas/TimeFrameEnum'
        strategy:
          $ref: '#/components/schemas/StrategyEnum'
        stamp:
          type: string
          format: date-time
        prodWins:
          type: integer
        prodLoses:
          type: integer
        prodTotal:
          type: integer
        prodWinPercentage:
          type: number
        devWins:
          type: integer
        devLoses:
          type: integer
        devTotal:
          type: integer
        devWinPercentage:
          type: number
